### ISSUE TITLE
Jobs not working properly due peds go missing

### ISSUE THREAD

**Issue by PatalJunior** [alp1x/um-fpsbooster#1]
All jobs that rely on ped interaction get broken due the SetEntityAsNoLongerNeeded(), because when they are of screen they just leave their zone, or despawns.

**Comment by cfunkz** [comment]
Yes got the same problem. Otherwise works great

**Comment by FiveOPZ** [comment]
same issue

**Comment by alp1x** [comment]
https://github.com/alp1x/um-fpsbooster/blob/main/lua/client.lua
